-- Copied seed for first-run import
-- If VITE_SEED_SQL not set, app attempts /seed.sql
-- Keep small; trim if needed

-- SQLite export generated by migration_tracking (truncated or full as needed)
PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

-- (You can replace this file contents with a minimal seed if desired.)

