// Utilities to export app data to JSON and SQLite SQL

function escapeSQLString(str) {
  return String(str).replace(/'/g, "''");
}

export function buildSnapshot(store) {
  // Build a stable snapshot of the data for export
  const baseProjects = store.projects.map(p => ({
    id: p.id,
    name: p.name,
    type: p.type,
    stage: p.stage,
    createdAt: p.createdAt,
    startedAt: p.startedAt || null,
    completedAt: p.completedAt || null,
    targetDays: p.targetDays,
    assignedDev: p.assignedDev
  }));
  // Merge developers: active list + any referenced in projects (covers historical/removed devs)
  const devSet = new Set(store.developers);
  baseProjects.forEach(p => { if (p.assignedDev) devSet.add(p.assignedDev); });
  const developers = Array.from(devSet);
  // Stage WIP limits (only numeric values)
  const stageWipLimits = {};
  const stageMap = store.stageWipLimits || {};
  Object.keys(stageMap).forEach(k => {
    const v = Number(stageMap[k]);
    if (Number.isFinite(v) && v > 0) stageWipLimits[k] = v;
  });
  const snapshot = {
    version: 1,
    exportedAt: new Date().toISOString(),
    targetAllCompletionDate: store.targetAllCompletionDate,
    developers,
    wipLimits: { ...store.wipLimits },
    stageWipLimits,
    projects: baseProjects
  };
  return snapshot;
}

export function buildExportJSON(snapshot) {
  return JSON.stringify(snapshot, null, 2);
}

export function buildExportSQLiteSQL(snapshot) {
  // Map developers to ids
  const devId = new Map();
  snapshot.developers.forEach((d, i) => devId.set(d, i + 1));
  const lines = [];
  lines.push('-- SQLite export generated by migration_tracking');
  lines.push('PRAGMA foreign_keys = ON;');
  lines.push('BEGIN TRANSACTION;');
  lines.push('');
  // Schema
  lines.push('CREATE TABLE IF NOT EXISTS devs (');
  lines.push('  id INTEGER PRIMARY KEY,');
  lines.push('  name TEXT NOT NULL UNIQUE,');
  lines.push('  wip_limit INTEGER');
  lines.push(');');
  lines.push('');
  lines.push('CREATE TABLE IF NOT EXISTS projects (');
  lines.push('  id INTEGER PRIMARY KEY,');
  lines.push("  name TEXT NOT NULL,");
  lines.push("  type TEXT NOT NULL CHECK (type IN ('migration','newbuild')),");
  lines.push("  stage TEXT NOT NULL CHECK (stage IN ('planning','template_build','review','final_updates','production','canceled')),");
  lines.push('  created_at TEXT NOT NULL,');
  lines.push('  started_at TEXT NULL,');
  lines.push('  completed_at TEXT NULL,');
  lines.push('  target_days INTEGER NOT NULL,');
  lines.push('  assigned_dev_id INTEGER NULL,');
  lines.push('  FOREIGN KEY (assigned_dev_id) REFERENCES devs(id) ON UPDATE CASCADE');
  lines.push(');');
  lines.push('');
  lines.push('CREATE TABLE IF NOT EXISTS settings (');
  lines.push('  key TEXT PRIMARY KEY,');
  lines.push('  value TEXT');
  lines.push(');');
  lines.push('');
  // Clear existing
  lines.push('DELETE FROM projects;');
  lines.push('DELETE FROM devs;');
  lines.push('DELETE FROM settings;');
  lines.push('');
  // Insert devs
  snapshot.developers.forEach((name) => {
    const id = devId.get(name);
    const wip = Object.prototype.hasOwnProperty.call(snapshot.wipLimits, name)
      ? snapshot.wipLimits[name]
      : null;
    const wipSQL = wip === null || wip === undefined || Number.isNaN(Number(wip)) ? 'NULL' : String(Number(wip));
    lines.push(`INSERT INTO devs (id, name, wip_limit) VALUES (${id}, '${escapeSQLString(name)}', ${wipSQL});`);
  });
  lines.push('');
  // Insert projects
  snapshot.projects.forEach((p) => {
    const dev = p.assignedDev ? devId.get(p.assignedDev) : null;
    // For safety, if a developer somehow wasn't mapped, create a placeholder
    if (p.assignedDev && !dev) {
      const newId = snapshot.developers.length + 1;
      const placeholder = p.assignedDev || 'Unknown';
      if (!devId.has(placeholder)) {
        devId.set(placeholder, newId);
        lines.push(`INSERT INTO devs (id, name, wip_limit) VALUES (${newId}, '${escapeSQLString(placeholder)}', NULL);`);
      }
    }
    const devFk = p.assignedDev ? devId.get(p.assignedDev) : null;
    const started = p.startedAt ? `'${escapeSQLString(p.startedAt)}'` : 'NULL';
    const completed = p.completedAt ? `'${escapeSQLString(p.completedAt)}'` : 'NULL';
    const devSql = devFk ? String(devFk) : 'NULL';
    lines.push(
      `INSERT INTO projects (id, name, type, stage, created_at, started_at, completed_at, target_days, assigned_dev_id) VALUES (` +
      `${p.id}, '${escapeSQLString(p.name)}', '${escapeSQLString(p.type)}', '${escapeSQLString(p.stage)}', ` +
      `'${escapeSQLString(p.createdAt)}', ${started}, ${completed}, ${Number(p.targetDays)}, ${devSql}` +
      `);`
    );
  });
  lines.push('');
  // Settings
  if (snapshot.targetAllCompletionDate) {
    lines.push(
      `INSERT INTO settings (key, value) VALUES ('target_all_completion_date', '${escapeSQLString(snapshot.targetAllCompletionDate)}');`
    );
  }
  if (snapshot.stageWipLimits && Object.keys(snapshot.stageWipLimits).length) {
    const json = escapeSQLString(JSON.stringify(snapshot.stageWipLimits));
    lines.push(
      `INSERT INTO settings (key, value) VALUES ('stage_wip_limits', '${json}');`
    );
  }
  lines.push('');
  lines.push('COMMIT;');
  lines.push('');
  return lines.join('\n');
}
